#! /bin/sh
# This script is for Solr Search Server Login
# set Variables
ssh=/usr/bin/ssh
user=solradmin
stg=10.0.102.11
prd31=10.0.101.31
prd32=10.0.101.32
clear
echo "############################################"
echo   "Please enter IP"
echo "############################################"
read ip

if [ $ip = stg ]
then
ssh $user@stg

else
if [ $ip = prd31 ]
then
ssh $user@prd31

else 
if [ $ip = prd32 ]
then
ssh $user@prd32

fi
fi
fi
clear
